In [2]:
# 1、一行代码实现1--100之和
# sum()
sum(range(1,101))

5050

In [3]:
# 2、如何在一个函数内部修改全局变量
# global
def fn():
    global a
    a = 4

In [7]:
# 4、字典如何删除键和合并两个字典
# del和update方法
dic = {"name":"jhon","age":18}
del dic["name"] #删除键
print(dic)
dic2 = {"name":"kitty"} # 合并
dic.update(dic2)
print(dic)

{'age': 18}
{'age': 18, 'name': 'kitty'}


In [8]:
# 6、python实现列表去重的方法
# 先通过集合去重，在转列表
lst = [11,15,18,85,18,15,12,12]
a = set(lst)
print(a)
[x for x in a]

{11, 12, 15, 18, 85}


[11, 12, 15, 18, 85]

In [9]:
# 13、列表[1,2,3,4,5],请使用map()函数输出[1,4,9,16,25]，并使用列表推导式提取出大于10的数，最终输出[16,25]
lst = [1,2,3,4,5]
def fn(x):
    return x**2
lst2 = map(fn,lst)
print(lst2)
[x for x in lst2 if x > 10]

[16, 25]

In [14]:
# 14、python中生成随机整数、随机小数、0--1之间小数方法
print(np.random.rand()) #生成一个随机数
print(np.random.rand(2,3)) #生成2*3随机数
print(np.random.randint(2,6)) #在2-6内生成一个随机整数
print(np.random.randint(2,16,2)) #在2-16内生成2个随机整数
print(np.random.randn()) #生成一个随机正泰分布的数
print(np.random.randn(2,4)) #生成2*4随机正泰分布的数
print(np.random.choice([10,20,30,40,60])) #生成给定一些数中的一个随机数

0.7304629702567088
[[0.97185559 0.71918931 0.91478381]
 [0.54141396 0.0764897  0.68787949]]
2
[2 8]
-0.24314266119074238
[[-3.57196788 -0.45720875  0.61507946  2.01341022]
 [-0.17883957 -1.53589475  0.07433281  0.5039946 ]]
40


In [15]:
# 15、避免转义给字符串加哪个字母表示原始字符串？
# r , 表示需要原始字符串，不转义特殊字符
print("this is \t and ...")
print(r"this is \t and ...")

this is 	 and ...
this is \t and ...


In [16]:
# 21、列出python中可变数据类型和不可变数据类型，并简述原理
# 不可变数据类型：数值型、字符串型string和元组tuple
# 不允许变量的值发生变化，如果改变了变量的值，相当于是新建了一个对象，而对于相同的值的对象，在内存中则只有一个对象（一个地址），
# 可变数据类型：列表list和字典dict；
# 允许变量的值发生变化，即如果对变量进行append、+=等这种操作后，只是改变了变量的值，而不会新建一个对象，
b = 10
print(id(b))
a = [1,2,3]
print(id(a))

140733338133168
1895813950536


In [23]:
# 22、s = "ajldjlajfdljfddd"，去重并从小到大排序输出"adfjl"
s = "ajldjlajfdljfddd"
goal = "adfjl"
a = list(set(s)) # set去重 list排序
print(a)
a.sort()
print(a)
res = "".join(a) # 列表转换成字符串拼接
print(res)
print(res == goal)

['d', 'f', 'l', 'a', 'j']
['a', 'd', 'f', 'j', 'l']
adfjl
True


In [24]:
# 23、用lambda函数实现两个数相乘
muti = lambda a, b: a*b
print(muti(3,4))

12


In [35]:
# 24、字典根据键从小到大排序
dic={"name":"zs","age":18,"city":"深圳","tel":"1362626627"}
print(dic.items())
print(dic.keys())# 键
print(dic.values())# 值
print(sorted(dic)) # 按键排序 只输出键
print(sorted(dic.items())) #输出全部内容

dict_items([('name', 'zs'), ('age', 18), ('city', '深圳'), ('tel', '1362626627')])
dict_keys(['name', 'age', 'city', 'tel'])
dict_values(['zs', 18, '深圳', '1362626627'])
['age', 'city', 'name', 'tel']
[('age', 18), ('city', '深圳'), ('name', 'zs'), ('tel', '1362626627')]


In [44]:
# 26、字符串a = "not 404 found 张三 99 深圳"，每个词中间是空格，用正则过滤掉英文和数字，最终输出"张三 深圳"
import re
a = "not 404 found 张三 99 深圳"
lst = list(a.split())
print(lst)
res = re.findall('\d+|[a-zA-Z]+',a)
print(res)
for i in res:
    if i in lst:
        lst.remove(i)
str = " ".join(lst)
print(str)

['not', '404', 'found', '张三', '99', '深圳']
['not', '404', 'found', '99']
张三 深圳


In [46]:
# 27、filter方法求出列表所有奇数并构造新列表，a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# filter() 函数用于过滤序列，过滤掉不符合条件的元素，返回由符合条件元素组成的新列表。
# 该接收两个参数，第一个为函数，第二个为序列，序列的每个元素作为参数传递给函数进行判断，
# 然后返回 True 或 False，最后将返回 True 的元素放到新列表
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
def fn(a):
    return a%2 == 1
lst = filter(fn,a)
lst = [i for i in lst]
print(lst)

[1, 3, 5, 7, 9]


In [47]:
# 28、列表推导式求列表所有奇数并构造新列表，a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lst = [i for i in a if i%2==1]
print(lst)

[1, 3, 5, 7, 9]


In [50]:
# 30、a=（1，）b=(1)，c=("1") 分别是什么类型的数据？
a=(1,)
b=(1)
c=("1") 
print(type(a),type(b),type(c))

<class 'tuple'> <class 'int'> <class 'str'>


In [52]:
# 31、两个列表[1,5,7,9]和[2,2,6,8]合并为[1,2,2,5,6,7,8,9]
a = [1,5,7,9]
b = [2,2,6,8]
c = a + b
c.sort()
print(c)

[1, 2, 2, 5, 6, 7, 8, 9]


In [56]:
# 33、log日志中，我们需要用时间戳记录error,warning等的发生时间，请用datetime模块打印当前时间戳 “2018-04-01 11:38:54”
import datetime
a = datetime.datetime.now()
print(a)

2020-04-22 16:20:01.800406


In [58]:
# 36、写一段自定义异常代码
# 自定义异常用raise抛出异常
def fn():
    try:
        for i in range(5):
            if i > 2 :
                raise Exception("数字大于2了")
    except Exception as ret:
        print(ret)
fn()

数字大于2了


In [65]:
# 37、正则表达式匹配中，（.*）和（.*?）匹配区别？
#（.*）是贪婪匹配，会把满足正则的尽可能多的往后匹配
#（.*?）是非贪婪匹配，会把满足正则的尽可能少匹配
s = "aa哈哈bbaa呵呵bb"
import re
res1 = re.findall("aa(.*)bb",s)
res2 = re.findall("aa(.*?)bb",s)
print(res1)
print(res2)

['哈哈bbaa呵呵']
['哈哈', '呵呵']


In [69]:
# 39、[[1,2],[3,4],[5,6]]一行代码展开该列表，得出[1,2,3,4,5,6]
# 列表推导式的骚操作
# 运行过程：for i in a ,每个i是【1,2】，【3,4】，【5,6】，for j in i，每个j就是1,2,3,4,5,6,合并后就是结果
a =[[1,2],[3,4],[5,6]]
import numpy as np
lst = np.array(a).flatten().tolist()
print(lst)
print(np.array(a).ravel().tolist())

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


In [75]:
# 40、x="abc",y="def",z=["d","e","f"],分别求出x.join(y)和x.join(z)返回的结果
# join()括号里面的是可迭代对象，x插入可迭代对象中间，形成字符串，结果一致，有没有突然感觉字符串的常见操作都不会玩了
x="abc"
y="def"
z=["d","e","f"]
print(x+y)
print(x+"".join(z))

abcdef
abcdef


In [76]:
# 42、python中交换两个数值
a = 2
b = 3
a,b = b,a
print(a,b)

3 2


In [78]:
# 43、举例说明zip（）函数用法
# zip()函数在运算时，会以一个或多个序列（可迭代对象）做为参数，返回一个元组的列表。同时将这些序列中并排的元素配对。
# zip()参数可以接受任何类型的序列，同时也可以有两个以上的参数;当传入参数的长度不同时，zip能自动以最短序列长度为准进行截取，获得元组。
a = [1,2,3]
b = [3,4]
print([i for i in zip(a,b)])
c = (1,2)
d = (3,4,5)# 根据最短 自动截取长度
print([i for i in zip(c,d)])
s1 = "abc"
s2 = "xy"
print([i for i in zip(s1,s2)])

[(1, 3), (2, 4)]
[(1, 3), (2, 4)]
[('a', 'x'), ('b', 'y')]


In [80]:
# 44、a="张明 98分"，用re.sub，将98替换为100
a="张明 98分"
import re
ret = re.sub(r"\d+","100",a)
print(ret)

张明 100分


In [81]:
#46、a="hello"和b="你好"编码成bytes类型
a="hello"
b="你好"
print(a.encode())
print(b.encode())

b'hello'
b'\xe4\xbd\xa0\xe5\xa5\xbd'


In [82]:
# 47、[1,2,3]+[4,5,6]的结果是多少？ 两个列表相加，等价于extend
print([1,2]+[3,4])

[1, 2, 3, 4]


In [85]:
# 52、list=[2,3,5,4,9,6]，从小到大排序，不许用sort，输出[2,3,4,5,6,9]
# 利用min()方法求出最小值，原列表删除最小值，新列表加入最小值，递归调用获取最小值的函数，反复操作
lst=[2,3,5,4,9,6]
new_lst=[]
def fn(lst):
    a = min(lst)
    new_lst.append(a)
    lst.remove(a)
    if len(lst)>0:
        fn(lst)
    return new_lst
new_lst = fn(lst)
print(new_lst)

[2, 3, 4, 5, 6, 9]


In [86]:
# 54、保留两位小数
a = 5
b = 3
print(round(a/3,2))

1.67


In [90]:
# 55、求三个方法打印结果
# fn("one",1）直接将键值对传给字典；
# fn("two",2)因为字典在内存中是可变数据类型，所以指向同一个地址，传了新的额参数后，会相当于给字典增加键值对
# fn("three",3,{})因为传了一个新字典，所以不再是原先默认参数的字典
def fn(k,v,dic={}):
    dic[k]=v
    print(dic)
print(fn("one",1))
print(fn("two",2))
print(fn("three",3,{}))

{'one': 1}
None
{'one': 1, 'two': 2}
None
{'three': 3}
None


In [92]:
# 58、使用pop和del删除字典中的"name"字段，dic={"name":"zs","age":18}
dic={"name":"zs","age":18}
del dic["name"]
print(dic)
dic={"name":"zs","age":18}
dic.pop("name")
print(dic)

{'age': 18}
{'age': 18}


In [101]:
# 60、计算代码运行结果，zip函数历史文章已经说了，得出[("a",1),("b",2)，("c",3),("d",4),("e",5)]
c = zip(["a","b","c","d","e"],[1,2,3,4,5])
print([i for i in c])
c = zip(["a","b","c","d","e"],[1,2,3,4,5])
print(dict(c))

[('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)]
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}


In [102]:
# 69、请将[i for i in range(3)]改成生成器
# 生成器是特殊的迭代器，
# 1、列表表达式的[]改为()即可变成生成器
# 2、函数在返回值得时候出现yield就变成生成器，而不是函数了；
# 中括号换成小括号即可，有没有惊呆了
a = (i for i in range(3))
type(a)

<generator object <genexpr> at 0x000001B96B1530C8>

In [103]:
# 70、a = " hehheh ",去除首尾空格
a = " hehheh "
print(a.strip())

hehheh


In [105]:
# 71、举例sort和sorted对列表排序，list=[0,-1,3,-10,5,9]
lst=[0,-1,3,-10,5,9]
lst.sort()
print(lst)

lst=[0,-1,3,-10,5,9]
lst = sorted(lst)
print(lst)

[-10, -1, 0, 3, 5, 9]
[-10, -1, 0, 3, 5, 9]


In [114]:
# 73、使用lambda函数对list排序foo = [-5,8,0,4,9,-4,-20,-2,8,2,-4]，输出结果为
# [0,2,4,8,8,9,-2,-4,-4,-5,-20]，正数从小到大，负数从大到小
foo = [-5,8,0,4,9,-4,-20,-2,8,2,-4]
a = sorted(foo,key=lambda x:(x<0,abs(x)))
print(a)
# print(sorted(foo,key=lambda x:abs(x)))
# print(sorted(foo,key=lambda x:x<0))

b = [i for i in a if i > 0]
b.sort()
print(b)
c = [i for i in a if i < 0]
c.sort(reverse=True)
print(c)
print(b+c)

[0, 2, 4, 8, 8, 9, -2, -4, -4, -5, -20]
[2, 4, 8, 8, 9]
[-2, -4, -4, -5, -20]
[2, 4, 8, 8, 9, -2, -4, -4, -5, -20]
